/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrintRouteImport } from './routes/print'
import { Route as AnnouncerRouteImport } from './routes/announcer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoundEventIdRoundIdRouteImport } from './routes/round.$eventId.$roundId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncerRoute = AnnouncerRouteImport.update({
  id: '/announcer',
  path: '/announcer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundEventIdRoundIdRoute = RoundEventIdRoundIdRouteImport.update({
  id: '/round/$eventId/$roundId',
  path: '/round/$eventId/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcer': typeof AnnouncerRoute
  '/print': typeof PrintRoute
  '/search': typeof SearchRoute
  '/round/$eventId/$roundId': typeof RoundEventIdRoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcer': typeof AnnouncerRoute
  '/print': typeof PrintRoute
  '/search': typeof SearchRoute
  '/round/$eventId/$roundId': typeof RoundEventIdRoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcer': typeof AnnouncerRoute
  '/print': typeof PrintRoute
  '/search': typeof SearchRoute
  '/round/$eventId/$roundId': typeof RoundEventIdRoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcer'
    | '/print'
    | '/search'
    | '/round/$eventId/$roundId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/announcer' | '/print' | '/search' | '/round/$eventId/$roundId'
  id:
    | '__root__'
    | '/'
    | '/announcer'
    | '/print'
    | '/search'
    | '/round/$eventId/$roundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncerRoute: typeof AnnouncerRoute
  PrintRoute: typeof PrintRoute
  SearchRoute: typeof SearchRoute
  RoundEventIdRoundIdRoute: typeof RoundEventIdRoundIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcer': {
      id: '/announcer'
      path: '/announcer'
      fullPath: '/announcer'
      preLoaderRoute: typeof AnnouncerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round/$eventId/$roundId': {
      id: '/round/$eventId/$roundId'
      path: '/round/$eventId/$roundId'
      fullPath: '/round/$eventId/$roundId'
      preLoaderRoute: typeof RoundEventIdRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncerRoute: AnnouncerRoute,
  PrintRoute: PrintRoute,
  SearchRoute: SearchRoute,
  RoundEventIdRoundIdRoute: RoundEventIdRoundIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
