/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrintRouteImport } from './routes/print'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnnouncerRouteImport } from './routes/announcer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintClubRouteImport } from './routes/print.club'
import { Route as AthleteKeyRouteImport } from './routes/athlete.$key'
import { Route as RoundEventIdRoundIdRouteImport } from './routes/round.$eventId.$roundId'
import { Route as ApiPublicHooksHarvestResultsRouteImport } from './routes/api/public/hooks/harvest-results'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncerRoute = AnnouncerRouteImport.update({
  id: '/announcer',
  path: '/announcer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintClubRoute = PrintClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => PrintRoute,
} as any)
const AthleteKeyRoute = AthleteKeyRouteImport.update({
  id: '/athlete/$key',
  path: '/athlete/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundEventIdRoundIdRoute = RoundEventIdRoundIdRouteImport.update({
  id: '/round/$eventId/$roundId',
  path: '/round/$eventId/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHarvestResultsRoute =
  ApiPublicHooksHarvestResultsRouteImport.update({
    id: '/api/public/hooks/harvest-results',
    path: '/api/public/hooks/harvest-results',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcer': typeof AnnouncerRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/watch': typeof WatchRoute
  '/athlete/$key': typeof AthleteKeyRoute
  '/print/club': typeof PrintClubRoute
  '/round/$eventId/$roundId': typeof RoundEventIdRoundIdRoute
  '/api/public/hooks/harvest-results': typeof ApiPublicHooksHarvestResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcer': typeof AnnouncerRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/watch': typeof WatchRoute
  '/athlete/$key': typeof AthleteKeyRoute
  '/print/club': typeof PrintClubRoute
  '/round/$eventId/$roundId': typeof RoundEventIdRoundIdRoute
  '/api/public/hooks/harvest-results': typeof ApiPublicHooksHarvestResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcer': typeof AnnouncerRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/watch': typeof WatchRoute
  '/athlete/$key': typeof AthleteKeyRoute
  '/print/club': typeof PrintClubRoute
  '/round/$eventId/$roundId': typeof RoundEventIdRoundIdRoute
  '/api/public/hooks/harvest-results': typeof ApiPublicHooksHarvestResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcer'
    | '/login'
    | '/print'
    | '/reset-password'
    | '/search'
    | '/watch'
    | '/athlete/$key'
    | '/print/club'
    | '/round/$eventId/$roundId'
    | '/api/public/hooks/harvest-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcer'
    | '/login'
    | '/print'
    | '/reset-password'
    | '/search'
    | '/watch'
    | '/athlete/$key'
    | '/print/club'
    | '/round/$eventId/$roundId'
    | '/api/public/hooks/harvest-results'
  id:
    | '__root__'
    | '/'
    | '/announcer'
    | '/login'
    | '/print'
    | '/reset-password'
    | '/search'
    | '/watch'
    | '/athlete/$key'
    | '/print/club'
    | '/round/$eventId/$roundId'
    | '/api/public/hooks/harvest-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncerRoute: typeof AnnouncerRoute
  LoginRoute: typeof LoginRoute
  PrintRoute: typeof PrintRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  WatchRoute: typeof WatchRoute
  AthleteKeyRoute: typeof AthleteKeyRoute
  RoundEventIdRoundIdRoute: typeof RoundEventIdRoundIdRoute
  ApiPublicHooksHarvestResultsRoute: typeof ApiPublicHooksHarvestResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcer': {
      id: '/announcer'
      path: '/announcer'
      fullPath: '/announcer'
      preLoaderRoute: typeof AnnouncerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/club': {
      id: '/print/club'
      path: '/club'
      fullPath: '/print/club'
      preLoaderRoute: typeof PrintClubRouteImport
      parentRoute: typeof PrintRoute
    }
    '/athlete/$key': {
      id: '/athlete/$key'
      path: '/athlete/$key'
      fullPath: '/athlete/$key'
      preLoaderRoute: typeof AthleteKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round/$eventId/$roundId': {
      id: '/round/$eventId/$roundId'
      path: '/round/$eventId/$roundId'
      fullPath: '/round/$eventId/$roundId'
      preLoaderRoute: typeof RoundEventIdRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/harvest-results': {
      id: '/api/public/hooks/harvest-results'
      path: '/api/public/hooks/harvest-results'
      fullPath: '/api/public/hooks/harvest-results'
      preLoaderRoute: typeof ApiPublicHooksHarvestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PrintRouteChildren {
  PrintClubRoute: typeof PrintClubRoute
}

const PrintRouteChildren: PrintRouteChildren = {
  PrintClubRoute: PrintClubRoute,
}

const PrintRouteWithChildren = PrintRoute._addFileChildren(PrintRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncerRoute: AnnouncerRoute,
  LoginRoute: LoginRoute,
  PrintRoute: PrintRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  WatchRoute: WatchRoute,
  AthleteKeyRoute: AthleteKeyRoute,
  RoundEventIdRoundIdRoute: RoundEventIdRoundIdRoute,
  ApiPublicHooksHarvestResultsRoute: ApiPublicHooksHarvestResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
